### ISSUE TITLE
AppChooser: Show contractor actions

### ISSUE THREAD

**Issue by danirabbit** [elementary/portals#16]
## Problem

Apps can't access contractor without adding another sandbox hole and cross-platform apps likely will not implement contractor actions

## Proposal

List contractor actions in the portal so that they're automatically available to apps implementing this portal

**Comment by Marukesu** [comment]
The AppChooser portal is a backend implementation to be used by the others portals. we shouldn't show more choices than the ones we receive from the frontend.

We should write a Contractor portal instead. that one should call the AppChooser portal using contracts as choices.

**Comment by danirabbit** [comment]
Closing since there's a proposal for a share portal that makes more sense here
