### ISSUE TITLE
A way to easily test portals

### ISSUE THREAD

**Issue by danirabbit** [elementary/portals#17]
## Problem

It's kind of a pain to try to hunt down various apps to test portals and see if they're working as expected

## Proposal

If there exists a portal demo, we should document it here. Otherwise, we should write one.

## Prior Art

See Granite Demo or the Notifications demo

**Comment by cassidyjames** [comment]
I recall Flatpak folks showing off https://github.com/flatpak/qt-flatpak-demo, but I think a large part of that was to demo that Qt apps could use the portals and feel native. It doesn't cover many portals in practice.

It would probably make sense to have our own portal demo app.

**Comment by tintou** [comment]
There is a test app in https://github.com/flatpak/libportal/tree/master/portal-test

**Comment by Marukesu** [comment]
> There is a test app in https://github.com/flatpak/libportal/tree/master/portal-test

so:

```
flatpak-builder --user --install --from-git=https://github.com/flatpak/libportal build-dir build-aux/org.gnome.PortalTest.Gtk4.json
flatpak run org.gnome.PortalTest.Gtk4
```

**Comment by danirabbit** [comment]
Closing because there's ASHPD Demo: https://flathub.org/apps/com.belmoussaoui.ashpd.demo
