### ISSUE TITLE
AppChooser doesn't work with mouse

### ISSUE THREAD

**Issue by janxkoci** [elementary/portals#52]
### What Happened?

It seems I cannot use mouse (touchpad) to select apps in AppChooser portal, only keyboard works (arrows up and down, then Enter).

The AppChooser portal is usually triggered when I want to open some file, e.g. after downloading it with Epiphany and clicking on it in the downloads popover, or when opening a file from archive in File Roller.

One example:

![Snímek z 2022-04-23 15-27-07](https://user-images.githubusercontent.com/19331850/164896597-ddc7a274-36fd-4d16-b0c9-e65f356ab1a8.png)

### Steps to Reproduce

1. Trigger the AppChooser portal (e.g. download a file with Epiphany and try to open it from popover, or open some zip archive and right-click some file inside it to "open" it);
2. AppChooser opens;
3. Try to select an app with mouse click.

### Expected Behavior

The app is selected and I can click the "Open" button to open it. I should also be able to double-click the app in the list to directly open it (thus skipping the "Open" button).

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

This is on a Slimbook Essential 14" laptop and its built-in touchpad.

![Snímek z 2022-03-21 10-48-39](https://user-images.githubusercontent.com/19331850/164896410-9d140a56-7c39-4df2-b733-876b66bec7ef.png)

**Comment by lenemter** [comment]
Can confirm on OS 7

**Comment by ryonakano** [comment]
I think this is because we're adding the entire of the window as the WindowHandle, which seems to override the button press event:

https://github.com/elementary/portals/blob/147ba3b67086211df0d1896df97a66990ff9b655/src/AppChooser/Dialog.vala#L139-L153

The similar issue was seen in IconBrowser and fixed in https://github.com/elementary/iconbrowser/pull/21, so maybe we can fix this in the similar way too?

**Comment by treppenwitz03** [comment]
If I am not mistaken, window handle has above_child property inherited from Gtk.EventBox, but it would not be ideal since we cannot use it anymore when we port to GTK4. I think the fix done in iconbrowser will do.
