### ISSUE TITLE
i18n: right to translate

### ISSUE THREAD

**Issue by ensag-dev** [elementary/portals#55]
### What Happened?

Hello,
I'd like to translate Portals using weblate but apparently I don't have enough right at the moment.
I want to complete the occitan translation.

Regards

### Steps to Reproduce

Going to weblate

### Expected Behavior

Can translate

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by tintou** [comment]
Hi there, as per the translation guide: https://elementary.io/docs/translation-guide#translation-guide
> By default, you're only able to suggest translations. If you would like to get permissions to save translations, [join the translators Slack](https://translators-slack.elementary.io/) and message an admin your Weblate username and what language you want to translate.

**Comment by ensag-dev** [comment]
Hello, I will make suggestion then, and you can review. I don't have slack

**Comment by danrabbit** [comment]
Hey @ensag-dev, we're trying to migrate the l10n community to [Matrix](https://matrix.to/#/%23elementary-l10n%3Amatrix.org). Not sure if that works better for you. You can also drop your weblate username and the language you're looking for approval for here and I can help you that way :)

**Comment by danirabbit** [comment]
Closing since there hasn't been comments here in several months
