### ISSUE TITLE
Granite.ActionSheet

### ISSUE THREAD

**Issue by danrabbit** [elementary/portals#56]
with app sandboxing, we have a couple of problems to keep in mind for the near future:

* Apps will lose access to seeing which other apps are installed. This means "Open in" submenus will no longer be possible.
* Apps will lose access to contractor. This means no "Other Actions" sub menu either.

I'd like to propose that in preparation for this, we create a Granite.ActionSheet as a protoype for an eventual portal implementation.

This should be a kind of universal dialog that gives the user options for opening a file in another application or taking action upon it via contractor actions.

**Comment by Exalm** [comment]
Would be nice to have a contractor-like system cross-desktop btw :)

**Comment by marbetschar** [comment]
For Reference: There is https://github.com/elementary/portals/issues/49 which is related to this.

**Comment by danrabbit** [comment]
Yeah sorry, this should be closed as a duplicate of #49

@Exalm yeah, I started a conversation at LAS a couple years ago about extending the .desktop spec to include actions which take a file as an argument and it seemed like nobody was opposed. It just needs someone to sit down and work on it. But I think that would probably be the smoothest replacement
