### ISSUE TITLE
Background Portal Implementation

### ISSUE THREAD

**Issue by leolost2605** [elementary/portals#68]
### Problem

Currently the flatpak Background Portal isn't available in elementary as the GTK implementation was removed by default with [this release](https://github.com/flatpak/xdg-desktop-portal-gtk/releases/tag/1.10.0) as it depends on gnome-shell. However it is needed for the flatpak versions of e.g. Mail, Calendar and Tasks to request autostart.

### Proposal

Implement the background portal from scratch or tweak the GTK version to work without gnome-shell.

**Comment by Marukesu** [comment]
The DesktopIntegration interface in gala need to be finished before we can write a background portal implementation, in special, the get_running_applications method.

**Comment by leolost2605** [comment]
I'm not sure and not very familiar with DBus but eager to learn :) and using D-Spy I found a `GetRunningApplications` method at `/org/pantheon/gala/DesktopInterface` under the interface `org.pantheon.gala.DesktopIntegration` on the bus `org.pantheon.gala` and it seems to work for me... except for that it doesn't return apps running without a window which I wouldn't really consider blocking.
Or am I missing something here?
Otherwise I would try and work on implementing the portal :)
